[phases.setup]
# مرحله 1: نصب پکیج‌های سیستمی و خود پایتون
# python310 یا هر نسخه‌ای که در .python-version مشخص کردید.
# playwright-driver برای فراهم کردن وابستگی‌های سیستمی مرورگرها.
nixPkgs = ["playwright"]







[phases.install]
cmds = [

    "playwright install chromium", # فقط کرومیوم را برای تست سریعتر نصب کن

]
